
spring:
  profiles: real-db
  datasource:
        url: jdbc:mariadb://localhost:3306/spring
        username: root
        password: 201530231
        driverClassName: org.mariadb.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
        